### ISSUE TITLE
ПР4 (ломаная линия)

### ISSUE THREAD

**Issue by drxaos** [VolginN/angledLine#1]
1. infoPoint() - в джаве обычно для перевода объекта в строку служит метод toString(). Если код перевода не делает ничего "тяжелого" (типа обращения к файлам или к бд), то лучше переопределить им стандартный toString().
2. Аналогично вместо compare() лучше переопределить стандартный equals().
3. Зачем нужен countPointDefault, если длину массива можно узнать из line.length? Метод setDefaultCountPoint() вообще невозможно использовать, так как его нельзя вызвать до конструктора.

**Comment by VolginN** [comment]
исправил,можете глянуть изменения в последнем коммите
